server:
  host: 0.0.0.0
  port: 3000
  read_timeout: 5s
  write_timeout: 5s

database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: auth
  sslmode: disable
  params:
    timezone: UTC

auth:
  issuer: toolbox
  audience: auth-service
  secret: supersecret
  access_ttl: 15m
  refresh_ttl: 720h

log:
  level: info
  pretty: false

telemetry:
  service_name: auth-service
  enabled: false
  endpoint: localhost:4317

redis:
  addr: localhost:6379
  username: ""
  password: ""
  db: 0
